name: minio-client
version: master
summary: ls, cp, mkdir, mirror commands for filesystems and object storage.
description: |
  Minio Client (mc) provides a modern alternative to UNIX commands
  like ls, cat, cp, mirror, diff etc. It supports filesystems and
  Amazon S3 compatible cloud storage service (AWS Signature v2 and v4).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

apps:
  minio-client:
    command: mc
    plugs: [home, network, network-bind]
    aliases: [mc]

parts:
  mc:
    source: .
    plugin: go
    go-importpath: github.com/minio/mc
    after: [go]
  go:
    source-tag: go1.8.3
